### ISSUE TITLE
withLifecycle method doesn't have access to domNode

### ISSUE THREAD

**Issue by cloudship** [zanettin/incompose#18]
domNode is acccessiable when using onComponentDidMount passed from parent. But it isn't accessible when using compose > withLifecycle method.

**Comment by zanettin** [comment]
Hi @cloudship 
Thanks for your info. do you have some example code with a working solution? i‘ll then try to fix it 👍

**Comment by cloudship** [comment]
Hi @zanettin , nope, I didn't have a solution with incompose, so that I just passed down the lifecyle funtions from the parent node to get it work.

**Comment by zanettin** [comment]
ah no, i meant a working example using the „native“ way with inferno. so i can see, what you want to achieve with incompose :-)

**Comment by cloudship** [comment]
```
import { withLifecycle, compose } from 'incompose'

const MyComponent = ()=>(
  <div>
    hello world!
  </div>
)

const mountNotice = (el:Element)=>{
  console.log(el);
}

export default compose(
  withLifecycle({
    componentDidMount: mountNotice
  })
)(MyComponent)

```
```
const IdeaListPage = () => (
  <div>
    <MyCompnent/>
  </div>
)
```

the code above generates output: "undefined" 

but if I pass the lifecycle function from the parent node, it works.

```
const IdeaListPage = () => (
  <div>
    <MyCompnent onComponentDidMount={mountNotice}/>
  </div>
)
const mountNotice = (el:Element)=>{
  console.log(el);
}
```
this prints out: `<div>hello world!</div>`

**Comment by zanettin** [comment]
ah now i got it. thanks for the code. 

the problem is, that we're talking about 2 separate functionalities here. the working example is a custom callback for inferno **functional** components. in this case, you'll receive the `element` as first param on your callback function. on the other hand, **class** components and the incompose lifecylces are not receiving any params on the `componentDidMount` method on the class. that's why i can't forward anything to you unfortunately.

### docs from inferno about this topic
https://infernojs.org/docs/guides/components 
- functional lifecycles
- class component lifecycle methods

### suggestion
i can share this code snippet with you which should do what you want:
```
import { createElement } from "inferno-create-element";
import compose from "incompose/dist/compose";

// tiny HoC to use the functional lifecycles from within the component
const withLifecycle = config => component => props => createElement(component, { ...props, ...config });

const App = () => <h1>my super awesome component</h1>;

export default compose(
  withLifecycle({ 
    onComponentDidMount: (el) => console.log("mounted", el) 
  })
)(App);
```
